version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: latest
        commands:
            - echo "Installing phase..."
    post_build:
        commands:
            - echo "Post build"
artifacts:
    files:
        - "bot/**/*"
        - "bot.js"
        - "package.json"
        - "package-lock.json"
        - ".npmrc"
eb_codebuild_settings:
    CodeBuildServiceRole: arn:aws:iam::886723564473:role/service-role/codebuild-BKKKBot-service-role
    ComputeType: BUILD_GENERAL1_LARGE
    Image: aws/codebuild/standard:4.0
    Timeout: 10
