#!/bin/bash
cd /home/ubuntu/
mkdir ./local/
echo '{"token":"NjkxNTcwNTM0MTUyMTQyODUw.Xnh6Cw.eitqPI3698lcHbr8Z2R9guVylcM"}'>./local/auth.json
curl -sL https://deb.nodesource.com/setup_10.x -o nodesource_setup.sh
sudo bash nodesource_setup.sh
sudo apt install nodejs -y
sudo apt install build-essential
npm install forever -g
rm -f nodesource_setup.sh install