#!/bin/bash
cd /home/ubuntu || echo "prevent cd fatal error"
pkill -f bot.js || echo "process not running"
PATH=$PATH:`ls -td /opt/elasticbeanstalk/node-install/node-* | head -1`/bin || echo "path not set"
tmux new -d -s cotixBot 'node bot.js' || echo "prevent tmux fatal error"